{{- if and .Values.sshGitServers (not .Values.sshGitServersKeysExistingSecret) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-ssh-git-servers
type: Opaque
data:
{{- range $server := .Values.sshGitServers }}
  id_rsa-{{ $server.host }}: {{ $server.privateKey | b64enc | quote }}
{{- end }}
{{- end -}}
